server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://${MYSQLHOST:mysql.railway.internal}:${MYSQLPORT:3306}/${MYSQLDATABASE:railway}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:YSPotmZRkUYieGmnYGUwCNiqGTixezqe}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Fallback mail settings if profile is railway
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME:atiattendance@gmail.com}
spring.mail.password=${SMTP_PASSWORD:wbjfzldoczyiagxk}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true